version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=postgres

#  django:
#    build:
#      context: .
#      dockerfile: ./compose/django/Dockerfile-dev
#    command: /start-dev.sh
#    depends_on:
#      - postgres
#    environment:
#      - POSTGRES_USER=postgres
#      - USE_DOCKER=yes
#    volumes:
#      - .:/app
#    ports:
#      - "8000:8000"
#      - "80:8000"
#    links:
#      - postgres
#      - mailhog
#      - rabbitmq

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  pgadmin4:
    image: fenglc/pgadmin4
    ports:
      - "5050:5050"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
      - "8080:8080"

  jenkins:
    image: library/jenkins
    ports:
      - "50000:50000"
      - "8090:8080"
